#ifndef TCPSERVER_GLOBAL_H
#define TCPSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPSERVER_LIBRARY)
#  define TCPSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCPSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

enum ClientCommand {
    COMMAND_DO_REGISTRATION = 1,
    COMMAND_DO_AUTHORIZATION,
    COMMAND_SEND_PM,
    COMMAND_LOAD_USER_LIST,
    COMMAND_LOAD_MESSAGE_LIST
};

enum ServerCommand {
    COMMAND_SEND_REGISTRATION_STATUS = 1,
    COMMAND_SEND_AUTHORIZATION_STATUS,
    COMMAND_SEND_PERSONAL_DATA,
    COMMAND_SEND_USER_DATA,
    COMMAND_SEND_USER_LIST,
    COMMAND_SEND_MESSAGE_LIST,
    COMMAND_SEND_MESSAGE
};

#endif // TCPSERVER_GLOBAL_H
