#ifndef DBMANAGER_GLOBAL_H
#define DBMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>
#include <chrono>

#if defined(DBMANAGER_LIBRARY)
#  define DBMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#define DEBUG_MODE 1
#define LOG_START(MSG) if (DEBUG_MODE) { qDebug() << "START\t" << MSG; }
#define LOG_END(MSG)   if (DEBUG_MODE) { qDebug() << "END\t"   << MSG; }

#define DB_TYPE     "QSQLITE"
#define DB_HOSTNAME "MESSENGERDATABASE"
#define DB_NAME     "MESSENGER.db"

#define PRIVATE_MESSAGE_CHAT_TABLE_NAME           "PM_CHAT"
#define PRIVATE_MESSAGE_CHAT_TABLE_ID             "PM_CHAT_ID"
#define PRIVATE_MESSAGE_CHAT_TABLE_FIRST_USER_ID  "FIRST_USER_ID"
#define PRIVATE_MESSAGE_CHAT_TABLE_SECOND_USER_ID "SECOND_USER_ID"

#define MESSAGE_TABLE_NAME       "MESSAGE"
#define MESSAGE_TABLE_ID         "MESSAGE_ID"
#define MESSAGE_TABLE_PM_CHAT_ID "PM_CHAT_ID"
#define MESSAGE_TABLE_AUTHOR_ID  "USER_ID"
#define MESSAGE_TABLE_CONTENT    "CONTENT"
#define MESSAGE_TABLE_DATE       "DATE"

#define USER_TABLE_NAME        "USER"
#define USER_TABLE_ID          "USER_ID"
#define USER_TABLE_NIK         "NIK"
#define USER_TABLE_FIRST_NAME  "FIRST_NAME"
#define USER_TABLE_SECOND_NAME "SECOND_NAME"
#define USER_TABLE_PASSWORD    "PASSWORD"

#endif // DBMANAGER_GLOBAL_H
